### ISSUE TITLE
Optimise binary arithmetic operations for powers of 10

### ISSUE THREAD

**Issue by faheel** [faheel/BigInt#18]
* [x] `first * second`
  If any one of the operands is 10<sup>x</sup>, return the other operand appended by **x** zeroes.

* [x] `first / second`
  If the second operand is 10<sup>x</sup> (and is less than the first operand), return the first `size - x` digits of the first operand.

* [x] `first % second`
  If the second operand is 10<sup>x</sup> (and is less than the first operand), return the last **x** digits of the first operand.

**NOTE**: in the implementation of the operators, the first operand is `*this`, and the second operand is `num`.

**Comment by KingAkeem** [comment]
Would I be able to work on this?

**Comment by KingAkeem** [comment]
I'm not sure how you want the multiply to be optimized, I attempted to just append zeros based on the size of the number but that's much slower than normal multiplication. I don't think we can make it more optimized than the compiler without writing ASM.

**Comment by faheel** [comment]
Say you have `num1` and `num2` as the two `BigInt` operands. Then, if any one of them is found to be a power of 10 (say it's `num1),` you can append the zeroes at once instead of using a loop, like so:
```C++
num2.value.append(num1.value.begin() + 1, num1.value.end());
// or
num2.value += num1.value.substr(1);
```

**Comment by KingAkeem** [comment]
I should've thought a little more about how I could utilize the BigInt objects first. I'm going to try both of those out right now.

**Comment by Aakankshareddy** [comment]
Hi,would like to contribute. Should I implement it in math.hpp or create a separate file?

**Comment by faheel** [comment]
@Aakankshareddy The operators have already been defined in `operators/binary_arithmetic.hpp`. You have to add checks within the definitions of the operators that are mentioned at the top, using a function named `is_power_of_10()`, which you can define in `functions/utilities.hpp`.

**Comment by MagmaCode** [comment]
I gave it a try. Hope it is good enough.
The tests pass and run times also seem to have decreased, which is good.
