### ISSUE TITLE
Cannot assign string literal directly

### ISSUE THREAD

**Issue by KingAkeem** [faheel/BigInt#20]
There is no way of assigning a string literal to a BigInt directly. You can declare a BigInt and then assign a string literal but you can't do it at the same time.

For example, if I attempt:
`BigInt a = "12345"`
I get an error that says `error: invalid conversion from ‘const char*’ to ‘const long long int&’`

But this is legal:
`BigInt a;`
`a  = "12345"`
I can also do:
`BigInt a = (string) "12345"`

I think the solution to this would simply to add a constructor and assignment for
`BigInt(const char *)`
`BigInt& operator=(const char*)`

#### System info

* OS: Linux Mint 18.2 Cinnamon 64-bit
* Compiler: gcc 6.3.0

**Comment by faheel** [comment]
See #3.
