### ISSUE TITLE
Should is_valid_number be able to handle negative numbers?

### ISSUE THREAD

**Issue by braamBeresford** [faheel/BigInt#39]
Would it be useful if I implemented the ability to test if a negative number is valid or not. 
I think it would be best to insert it into the existing function.

**Comment by faheel** [comment]
It's not required as the [`BigInt` constructor that takes a string as the input](https://github.com/faheel/BigInt/blob/master/include/constructors/constructors.hpp#L55-L76) handles the sign separately, and the `is_valid_number` method is only used for checking whether the magnitude is a valid (whole) number.

**Comment by faheel** [comment]
@braamBeresford If you're interested in contributing then you can rename the function to `is_whole_number` and update its comment to `Checks whether the given string is a whole number`.
