### ISSUE TITLE
big_random might return a BigInt having a value with a leading 0

### ISSUE THREAD

**Issue by DThiebaud** [faheel/BigInt#40]
`big_random` might return a `BigInt` whose `value` has a leading `'0'`, which will cause problems.

**Comment by DThiebaud** [comment]
To make a truly uniform distribution, it is necessary to take the generated number and add leading-zeroes if needed.
Also, according to what I have read, std::random_device has limited entropy and should only be used for a random seed.
I have updates to random.hpp for this. Should I submit a pull request?

**Comment by faheel** [comment]
Sure, submit a PR and I'll review it.

**Comment by nos111** [comment]
Is this issue still open?
I would like to contribute by fixing it
