### ISSUE TITLE
Using I/O.

### ISSUE THREAD

**Issue by ABelmarM** [faheel/BigInt#8]
Wouldn't be redundant using overloaded operators like >> or << for I/O?, they could be used as bitwise operators in the future, especially considering you have a to_string() method which could serve as an out method, and one of yours constructors accepts a string as a parameter, you could just input a string and then call it.

**Comment by faheel** [comment]
The `<<` and `>>` are the standard input and output stream operators respectively in C++. They are used to input and output built-in types, and so it would be good to use them for I/O of a `BigInt` object.

In the future, we will still be able to use them for bit shifting as the bitwise shift operators `<<` and `>>` will have the signature `(int)`, which is different from the signatures of the I/O stream operators, which are `(std::istream&, BigInt&)` (for `<<`) and `(std::ostream&, const BigInt&)` (for `>>`). So, based on the signature, the compiler will be able to determine the right function to call when performing either I/O or bit shifting.
